within XRay.Objects.Electrical;

model Filament
  extends Resistor;
  
  output Modelica.Units.SI.Power P_elec "Power generated by heating"; // (W)
  
  Modelica.Units.SI.Power P;
  
equation

  //  Joule effect heat
  P = v*i;
  P_elec = P;
  
end Filament;